# -*- coding: utf-8 -*-
"""Segundo passe: distratores plausíveis, vários deles mais longos que a resposta certa."""
import json, re

B = json.load(open('/tmp/b.json', encoding='utf-8'))

NOVAS = {
603: (["Utilizar o frasco até o esgotamento do conteúdo, independentemente da data e do horário de abertura","Respeitar o prazo de validade após a abertura definido pelo fabricante e pelo PNI","Descartar o frasco logo após a retirada da primeira dose, ainda que restem doses aproveitáveis","Congelar o frasco já aberto para preservar a estabilidade do imunobiológico até o dia seguinte","Manter o frasco em temperatura ambiente até o encerramento do expediente da sala de vacinação"],1),
771: (["Ser adotada de rotina na admissão de todo paciente com agitação psicomotora ou risco de fuga","Ser utilizada após falha das medidas verbais e ambientais, com prescrição, monitorização e registro","Ser executada pela equipe de segurança patrimonial sempre que solicitada pela enfermagem do setor","Ser mantida por tempo indeterminado até a completa remissão do quadro de agitação apresentado","Ser realizada sem informar o paciente, para não aumentar a agitação durante o procedimento"],1),
638: (["Substituir parte do currículo escolar por conteúdos de educação em saúde definidos pelo município","Articular ações de saúde e educação no território, com avaliação clínica e promoção junto aos estudantes","Realizar campanhas periódicas de vacinação nas escolas da rede pública de ensino do território","Ser executado exclusivamente pelos professores, com apoio pontual da equipe de saúde da família","Atender somente as escolas privadas conveniadas, mediante contrapartida da rede municipal de ensino"],1),
850: (["Prestar assistência direta aos pacientes de maior complexidade, sem atribuições administrativas","Responder tecnicamente pelo serviço de enfermagem perante o COREN, zelando pelas normas","Administrar os recursos financeiros da instituição destinados ao serviço de enfermagem","Substituir o diretor clínico nas decisões assistenciais durante os períodos de ausência","Definir a política salarial e o plano de cargos e carreiras da equipe de enfermagem"],1),
180: (["Boca pouco aberta, lábios voltados para dentro e queixo afastado da mama durante a sucção","Queixo tocando a mama, boca bem aberta, lábio inferior evertido e mais aréola visível acima","Apenas o mamilo dentro da boca do bebê, com movimentos rápidos e superficiais de sucção","Bochechas encovadas a cada sucção, com pausas frequentes e sinais de cansaço do lactente","Ruído alto de estalo a cada sucção, acompanhado de dor referida pela nutriz durante a mamada"],1),
827: (["Idade materna entre vinte e trinta anos com acompanhamento pré-natal iniciado no primeiro trimestre","Hipertensão, diabetes prévio, cardiopatias e antecedente de prematuridade ou perdas fetais","Primeira gestação isoladamente, sem qualquer intercorrência clínica ou obstétrica associada","Ganho de peso adequado para o índice de massa corporal aferido antes do início da gestação","Náuseas e vômitos no primeiro trimestre com boa resposta às medidas dietéticas orientadas"],1),
737: (["Executar a transferência sozinho, independentemente do peso e da mobilidade do paciente","Travar as rodas, avaliar a capacidade do paciente, pedir apoio e usar dispositivos auxiliares","Tracionar o paciente pelos braços até a borda do leito, apoiando-o pelas articulações","Manter a cama em posição elevada para aproveitar a gravidade durante a transferência","Retirar o calçado do paciente antes da transferência para melhorar o apoio dos pés no chão"],1),
486: (["Internação de curta permanência para pessoas em crise psiquiátrica sem indicação hospitalar","Moradia de pessoas com transtorno mental egressas de longas internações, sem suporte familiar","Atendimento ambulatorial de crise em regime intensivo, com equipe multiprofissional própria","Reabilitação física e cognitiva de pessoas com sequelas neurológicas de longa evolução","Acolhimento noturno de urgência para pessoas em situação de rua com sofrimento psíquico"],1),
482: (["A criação do Sistema Único de Saúde e a definição de seus princípios e diretrizes gerais","A proteção e os direitos das pessoas com transtornos mentais e o redirecionamento do modelo assistencial","O exercício profissional da enfermagem nos serviços substitutivos de atenção psicossocial","A política nacional de medicamentos e a dispensação de psicofármacos na rede pública","O financiamento da atenção básica e a transferência de recursos aos fundos municipais"],1),
473: (["Uso correto e contínuo da medicação prescrita, com retornos regulares para ajuste de dose","Redução do sódio, controle do peso, atividade física regular e moderação no consumo de álcool","Redução das gorduras saturadas da dieta, mantidos os demais hábitos alimentares habituais","Restrição hídrica rigorosa ao longo do dia, com controle do volume urinário de vinte e quatro horas","Aumento do consumo de café e de bebidas estimulantes para melhorar a disposição diária"],1),
845: (["Restringir a autonomia dos residentes como medida de prevenção de quedas e de acidentes","Preservar a autonomia e a individualidade, com plano de cuidados e vínculo com a rede de saúde","Substituir integralmente o acompanhamento na atenção básica pelo cuidado prestado na instituição","Basear-se na contenção física durante a noite para reduzir o risco de deambulação sem supervisão","Restringir as visitas de familiares a horários fixos para preservar a rotina institucional"],1),
736: (["Realizar a higiene oral uma vez ao dia, no período da manhã, junto com o banho no leito","Realizar higiene sistemática, com antisséptico quando indicado, cabeceira elevada e aspiração disponível","Utilizar grande volume de líquido para garantir a remoção completa da placa bacteriana","Dispensar a aspiração quando o paciente estiver com o balonete adequadamente insuflado","Realizar o procedimento com o paciente em decúbito horizontal, para facilitar o acesso à cavidade"],1),
696: (["Apenas a vacina hepatite B prevista na rotina do calendário nacional de vacinação","Vacina hepatite B e imunoglobulina específica, preferencialmente nas primeiras doze horas de vida","Somente a imunoglobulina específica, administrada por volta do trigésimo dia de vida","Apenas acompanhamento sorológico seriado durante os primeiros doze meses de vida","Antiviral por seis meses associado ao acompanhamento ambulatorial especializado"],1),
673: (["Manter a cabeceira a zero grau para favorecer a perfusão cerebral do paciente neurocrítico","Manter a cabeça em posição neutra, cabeceira a cerca de trinta graus e evitar manobras que elevem a pressão","Realizar aspiração traqueal prolongada e frequente para prevenir acúmulo de secreções","Manter o pescoço levemente fletido, com apoio de coxim occipital, durante todo o período","Restringir a analgesia para permitir a avaliação neurológica seriada do nível de consciência"],1),
510: (["Coletar amostra de saliva em qualquer horário do dia, em recipiente limpo e identificado","Coletar material de expectoração profunda, preferencialmente ao despertar, em pote identificado","Coletar a amostra logo após alimentação abundante, para facilitar a mobilização de secreções","Coletar após bochecho com antisséptico bucal, para reduzir a contaminação por microbiota oral","Coletar apenas com o paciente em jejum absoluto de doze horas, como nos exames laboratoriais"],1),
453: (["Massagear vigorosamente as proeminências ósseas para estimular a circulação local da pele","Reposicionamento programado, superfície de suporte adequada, hidratação da pele e avaliação nutricional","Utilizar almofada tipo roda d'água na região sacral para aliviar a pressão sobre o local","Manter a cabeceira do leito sempre acima de quarenta e cinco graus para conforto respiratório","Friccionar a pele com álcool após o banho para promover a secagem e prevenir a umidade"],1),
636: ([" Transportar o bebê no colo de um adulto no banco traseiro durante deslocamentos curtos","Usar dispositivo de retenção adequado à idade e ao peso e nunca deixar o bebê em superfícies altas","Oferecer alimentos pequenos e duros para estimular o desenvolvimento da mastigação precoce","Deixar sacos e embalagens plásticas ao alcance como recurso de estímulo sensorial e visual","Aquecer a mamadeira em forno de micro-ondas para agilizar o preparo das mamadas noturnas"],1),
437: (["Retirar imediatamente o cateter e comprimir firmemente o local por alguns minutos","Interromper a infusão e aspirar o resíduo pelo cateter antes de retirá-lo, conforme protocolo","Aumentar a velocidade de infusão para diluir o medicamento extravasado nos tecidos","Aplicar compressa morna sobre a área acometida, independentemente do fármaco envolvido","Manter a infusão em curso e observar a evolução da área por até duas horas antes de agir"],1),
341: (["Substituir a maternidade na assistência ao parto de risco habitual em áreas desassistidas","Acolher gestantes, puérperas e bebês de risco que precisam permanecer próximos ao hospital","Funcionar como unidade básica de saúde voltada ao acompanhamento pré-natal de alto risco","Realizar exames de alta complexidade e procedimentos diagnósticos em gestação de risco","Atender exclusivamente gestantes adolescentes em situação de vulnerabilidade social"],1),
178: (["Ultrassonografia obstétrica precoce para datação da idade gestacional e avaliação embrionária","Hemograma, tipagem com fator Rh, glicemia, testes para sífilis, HIV, hepatites e exame de urina","Glicemia de jejum e hemograma completo, com repetição a cada trimestre da gestação","Sorologia para toxoplasmose, com repetição mensal nas gestantes suscetíveis identificadas","Exame de urina tipo I e coleta de citopatológico de colo uterino na primeira consulta"],1),
829: (["Decúbito ventral, que reduz o refluxo gastroesofágico e melhora o padrão respiratório","Decúbito dorsal, em superfície firme e sem objetos soltos no berço do lactente","Decúbito lateral apoiado por travesseiro ou rolo de tecido para manter a posição estável","Semissentado na cadeirinha ou no bebê conforto durante os períodos de sono diurno","Em rede ou berço com protetores acolchoados nas laterais para maior conforto e segurança"],1),
764: (["Reintroduzir cuidadosamente as vísceras na cavidade abdominal antes de cobrir a ferida","Cobrir com compressa estéril umedecida em solução salina, sem reintroduzir, e transportar","Aplicar compressa seca sobre as vísceras e comprimir firmemente para conter o sangramento","Deixar a região exposta ao ar ambiente até a avaliação pela equipe cirúrgica no hospital","Aplicar solução antisséptica diretamente sobre as vísceras expostas antes de cobri-las"],1),
738: (["Introduzir a sonda com firmeza e rapidez para reduzir o desconforto durante o procedimento","Posicionar o paciente em decúbito lateral esquerdo, lubrificar a sonda e infundir lentamente","Utilizar solução em temperatura baixa para estimular o peristaltismo e acelerar o efeito","Manter o frasco a mais de um metro e meio de altura para garantir a infusão do volume total","Realizar o procedimento sem necessidade de informar previamente o paciente sobre as etapas"],1),
708: (["O trabalho administrativo da unidade e o tempo dedicado ao preenchimento dos formulários","A qualidade do sistema de informação, o cálculo de indicadores e o planejamento das ações","O repasse de recursos federais vinculados ao cumprimento de metas de notificação","O registro individual do paciente e a continuidade do seu acompanhamento no serviço","A auditoria hospitalar e a conferência dos procedimentos faturados pela instituição"],1),
547: (["Sólido e formado, com frequência de eliminação semelhante à do hábito intestinal habitual","Líquido a pastoso, mais volumoso e rico em enzimas, com maior risco de dermatite periestomal","Ausente na maior parte dos casos, exigindo estímulo por irrigação intestinal programada","Semelhante ao de uma colostomia em sigmoide, com consistência pastosa e odor característico","Constituído por urina, exigindo dispositivo coletor com sistema antirrefluxo específico"],1),
536: (["Iniciar sempre por opioide forte, ajustando a dose conforme a resposta clínica do paciente","Progressão conforme a intensidade da dor, de não opioides a opioides fracos e fortes, com adjuvantes","Utilizar exclusivamente medidas não farmacológicas até a exaustão das alternativas disponíveis","Reservar a analgesia farmacológica aos pacientes com dor de origem oncológica confirmada","Iniciar com placebo na primeira etapa para avaliar o componente emocional da queixa álgica"],1),
523: (["A doença instalada e a resposta ao tratamento medicamentoso prescrito pelo profissional","O atendimento das necessidades humanas básicas afetadas, promovendo o autocuidado e o equilíbrio","A administração dos recursos hospitalares e a organização do processo de trabalho da equipe","O cumprimento da prescrição médica e o registro dos procedimentos realizados no prontuário","A pesquisa laboratorial aplicada ao desenvolvimento de novas tecnologias em enfermagem"],1),
851: (["Omitir o ocorrido para evitar sanções administrativas e desgaste com a equipe do setor","Comunicar imediatamente à equipe e à chefia, proteger o paciente e registrar o ocorrido","Corrigir o registro em prontuário de modo a ocultar a ocorrência da falha assistencial","Atribuir a falha ao profissional do plantão anterior, por não ter sido possível identificá-la","Aguardar que o evento seja identificado por terceiros antes de qualquer manifestação formal"],1),
810: (["Transmissão respiratória a partir de casos bacilíferos presentes no ambiente domiciliar","Contaminação do coto umbilical por práticas inadequadas no parto e no cuidado com o coto","Transmissão vertical por via placentária durante o terceiro trimestre de gestação","Transmissão pelo aleitamento materno em nutrizes sem esquema vacinal atualizado","Contato direto com outras crianças em ambientes coletivos de convivência infantil"],1),
725: (["Uso de agentes enzimáticos proteolíticos aplicados diretamente sobre o tecido desvitalizado","Remoção do tecido desvitalizado por ação física, como irrigação sob pressão ou curativo úmido-seco","Uso de instrumental cortante por profissional habilitado, em ambiente com técnica asséptica","Autólise promovida pelo próprio organismo, favorecida por coberturas que mantêm a umidade","Aplicação de calor local para amolecer o tecido necrótico e facilitar sua remoção posterior"],1),
417: (["Sede intensa com olhos de aspecto normal e mucosas discretamente ressecadas","Letargia ou inconsciência, olhos fundos, sinal da prega muito lento e incapacidade de beber","Diurese preservada, mucosas úmidas e enchimento capilar dentro dos parâmetros normais","Irritabilidade isolada, sem alteração do turgor cutâneo ou da aceitação de líquidos","Febre baixa isolada acompanhada de aumento discreto da frequência respiratória"],1),
346: (["Trata-se de exigência de natureza estritamente administrativa, sem repercussão clínica","Cabe à regulação identificar o recurso adequado e a vaga, evitando transferências sem destino","O médico assistente não detém competência clínica para indicar a transferência do paciente","O transporte inter-hospitalar é sempre realizado por meio aéreo, dada a gravidade dos casos","A família precisa autorizar formalmente o acionamento da central de regulação médica"],1),
824: (["Retirar o dispositivo a cada seis meses para avaliação da integridade e reinserção posterior","Informar sobre alterações do padrão menstrual e sinais de alerta, como dor intensa e febre","Evitar qualquer atividade física de impacto pelo risco de deslocamento do dispositivo","Realizar autoexame diário dos fios, com leve tração, para confirmar o posicionamento correto","Substituir o dispositivo mensalmente, conforme orientação do serviço de planejamento familiar"],1),
749: (["É a mesma para toda a população adulta, independentemente de comorbidades associadas","Varia conforme o risco cardiovascular do indivíduo, sendo mais rigorosa nos de alto risco","Depende exclusivamente da faixa etária, com valores progressivamente menores após os sessenta anos","É definida a partir do peso corporal e do índice de massa corporal aferidos na consulta","Não é utilizada na prática clínica, por não haver evidência que sustente metas numéricas"],1),
622: (["Oferecer métodos não farmacológicos de alívio da dor durante o trabalho de parto ativo","Impedir a presença do acompanhante, realizar procedimentos sem consentimento e usar linguagem desrespeitosa","Registrar a evolução da dilatação e da descida da apresentação no partograma da parturiente","Realizar ausculta fetal intermitente conforme o protocolo assistencial adotado no serviço","Orientar a mulher sobre o plano de parto e sobre as práticas disponíveis na maternidade"],1),
607: (["Ser realizada no mesmo dia, sem qualquer prejuízo para a resposta imunológica esperada","Respeitar um intervalo definido em protocolo, pelo risco de redução da resposta imune","Ser antecipada em relação ao calendário, para garantir a proteção antes da exposição","Ser cancelada em definitivo, com registro da contraindicação permanente na caderneta","Ser realizada em dose dobrada, para compensar a neutralização pelos anticorpos passivos"],1),
151: (["Protocolo assistencial padronizado por patologia, aplicado a todos os casos semelhantes","Conjunto de propostas terapêuticas construído pela equipe para um sujeito ou coletivo específico","Plano de metas administrativas da unidade, pactuado entre a gestão e os trabalhadores","Roteiro de classificação de risco utilizado no acolhimento da demanda espontânea diária","Escala de trabalho da equipe organizada conforme a complexidade dos casos acompanhados"],1),
614: (["Prevenir a anemia megaloblástica materna decorrente da maior demanda na gestação","Prevenir defeitos do tubo neural, devendo ser iniciada preferencialmente antes da concepção","Favorecer o ganho de peso fetal adequado no terceiro trimestre de gestação","Prevenir o desenvolvimento de diabetes mellitus gestacional em mulheres com risco aumentado","Reduzir a intensidade das náuseas e dos vômitos característicos do primeiro trimestre"],1),
299: (["O acesso a consultas médicas e a medicamentos oferecidos pela rede pública de saúde","Alimentação, moradia, saneamento, meio ambiente, trabalho, renda, educação, transporte e lazer","Os hábitos individuais relacionados a alimentação, atividade física e uso de substâncias","Os fatores genéticos e a predisposição hereditária a determinadas condições crônicas","A oferta de leitos hospitalares e a capacidade instalada dos serviços de média complexidade"],1),
49: (["Registrado apenas no prontuário do usuário e comunicado ao responsável pela sala de vacinação","Notificado ao sistema de vigilância, mesmo sem confirmação da relação causal com a vacina","Notificado somente nos casos que evoluírem para óbito ou internação hospitalar prolongada","Comunicado apenas ao fabricante do imunobiológico, para fins de controle de qualidade do lote","Investigado apenas quando ocorrer durante campanhas nacionais de vacinação em massa"],1),
846: (["Substitui o diagnóstico clínico na definição das condutas terapêuticas indicadas","É melhor preditor de desfechos que o diagnóstico isolado, orientando o plano de cuidados","Serve apenas para fins estatísticos e de produção de indicadores epidemiológicos locais","Aplica-se somente a pessoas idosas acamadas ou com dependência funcional já instalada","Depende exclusivamente da idade cronológica registrada no cadastro da unidade de saúde"],1),
812: (["Notificar todos os casos de todos os agravos ocorridos no território de abrangência","Monitorar eventos de saúde em unidades selecionadas, gerando informação oportuna sobre tendências","Substituir o sistema nacional de agravos de notificação nas unidades habilitadas","Ser realizada apenas em hospitais privados conveniados ao sistema público de saúde","Dispensar a notificação compulsória dos agravos monitorados pelas unidades participantes"],1),
765: (["Fratura de uma única costela com dor localizada à palpação e à inspiração profunda","Fraturas múltiplas de costelas em mais de um ponto, com movimento paradoxal do segmento","Pneumotórax simples decorrente de trauma fechado, sem repercussão hemodinâmica associada","Contusão pulmonar isolada com hipoxemia progressiva nas primeiras horas após o trauma","Fratura de esterno sem repercussão respiratória ou comprometimento de estruturas mediastinais"],1),
656: (["É livre, desde que o material seja submetido a processo de esterilização validado","É vedado para os produtos classificados e proibidos de reprocessamento pela ANVISA","É permitido por até três ciclos, com registro da rastreabilidade de cada reprocessamento","Depende da avaliação visual da integridade do material pelo profissional responsável","É decidido pela chefia de enfermagem conforme a disponibilidade de insumos no serviço"],1),
640: (["Substitui a higienização das mãos quando forem trocadas entre um paciente e outro","Não substitui a higienização das mãos, que deve ser feita antes de calçar e após retirar","Dispensa a troca entre pacientes, desde que não haja contato com fluidos corporais","Deve ser mantido durante todo o plantão para reduzir o consumo de material do setor","É indicado apenas na realização de procedimentos invasivos em pacientes internados"],1),
544: (["Tratamento dos casos humanos confirmados, com acompanhamento ambulatorial prolongado","Controle do vetor, manejo ambiental e diagnóstico e destinação adequada dos cães infectados","Vacinação humana em massa nas áreas com transmissão ativa registrada nos últimos anos","Notificação dos casos ao sistema de informação, com investigação epidemiológica posterior","Isolamento respiratório dos pacientes durante todo o período de tratamento específico"],1),
514: (["Reduzir a velocidade de infusão e observar a evolução do quadro por alguns minutos","Interromper imediatamente a transfusão, manter o acesso com solução salina e comunicar a equipe","Administrar antitérmico conforme prescrição e manter a infusão do hemocomponente em curso","Retirar o acesso venoso e puncionar novo sítio antes de comunicar o serviço de hemoterapia","Trocar a bolsa por outra do mesmo doador e reiniciar a infusão em velocidade reduzida"],1),
477: (["Índice de massa corporal elevado associado a circunferência abdominal aumentada","Obesidade abdominal associada a alterações de triglicerídeos, HDL, pressão arterial e glicemia","Glicemia de jejum alterada em duas aferições consecutivas realizadas em dias distintos","Hipertensão arterial em tratamento medicamentoso com controle pressórico inadequado","Colesterol total elevado com fração LDL acima da meta definida para o risco do paciente"],1),
821: (["Quadro mais grave e prolongado, com necessidade de acompanhamento psiquiátrico especializado","Quadro transitório, iniciado nos primeiros dias e com resolução espontânea em cerca de duas semanas","Quadro sempre acompanhado de ideação suicida e de risco imediato para a mãe e o bebê","Quadro restrito a primíparas com gestação não planejada e rede de apoio insuficiente","Quadro que indica internação hospitalar imediata em unidade de saúde mental de referência"],1),
739: (["Tracionar o fio pela porção externa, sem cortá-lo, até a completa remoção do ponto","Cortar o fio junto à pele e tracionar de modo que a parte externa não atravesse o trajeto interno","Cortar todos os pontos da ferida antes de iniciar a retirada, para agilizar o procedimento","Utilizar material limpo, não estéril, uma vez que a ferida já se encontra epitelizada","Retirar todos os pontos no terceiro dia de pós-operatório, independentemente da região"],1),
716: (["Dispensar qualquer proteção adicional durante o trajeto, por ser de curta duração","Colocar máscara cirúrgica no paciente, avisar o setor de destino e evitar esperas em áreas comuns","Transportar sem comunicação prévia, para não gerar atraso na realização do exame agendado","Utilizar apenas luvas de procedimento durante todo o deslocamento pelo corredor do serviço","Adiar o exame por tempo indeterminado até o encerramento do período de transmissibilidade"],1),
686: (["Inclinar a cabeça para trás e comprimir a raiz do nariz até o sangramento cessar","Comprimir as asas nasais por alguns minutos, com a cabeça levemente inclinada para frente","Introduzir algodão seco profundamente na narina acometida até conter o sangramento ativo","Posicionar o paciente em decúbito dorsal horizontal com os membros inferiores elevados","Aplicar compressa aquecida sobre o dorso do nariz para favorecer a hemostasia local"],1),
672: (["A saturação arterial de oxigênio medida de forma contínua por oximetria de pulso","A pressão de enchimento do lado direito do coração, auxiliando na avaliação volêmica","A pressão intracraniana estimada de forma indireta em pacientes com lesão neurológica","O débito urinário horário como indicador indireto da perfusão renal do paciente crítico","A resistência das vias aéreas durante o ciclo respiratório em ventilação mecânica"],1),
617: (["Presença de contrações uterinas de qualquer intensidade referidas pela gestante","Contrações uterinas regulares e efetivas associadas a modificações do colo uterino","Rotura espontânea da bolsa amniótica, independentemente das condições do colo","Perda do tampão mucoso acompanhada de desconforto pélvico e aumento das secreções","Dor lombar contínua de moderada intensidade com irradiação para a região inguinal"],1),
492: (["Cefaleia leve com sudorese e tremores finos de extremidades nas primeiras horas","Delirium tremens, com confusão, alucinações, tremores e instabilidade autonômica","Sonolência progressiva com redução do nível de consciência e resposta a estímulos","Hipotermia isolada acompanhada de bradicardia e vasoconstrição periférica intensa","Melhora espontânea em vinte e quatro horas, sem necessidade de intervenção clínica"],1),
429: (["Realizar a auditoria das contas hospitalares relacionadas ao uso de antimicrobianos","Elaborar e implantar o programa de controle de infecção, com vigilância epidemiológica das IRAS","Substituir a vigilância sanitária municipal na fiscalização das condições do estabelecimento","Prescrever os antimicrobianos aos pacientes internados conforme o perfil de sensibilidade","Gerenciar a escala de enfermagem nas unidades com maior incidência de infecções relacionadas"],1),
349: (["Lista dos medicamentos de uso exclusivo em ambiente hospitalar e em terapia intensiva","Relação dos medicamentos disponibilizados pelo SUS para atender às necessidades prioritárias","Tabela de preços máximos praticados na venda de medicamentos ao consumidor final","Lista dos medicamentos com comercialização proibida em território nacional pela ANVISA","Cadastro das farmácias privadas credenciadas para dispensação de medicamentos do SUS"],1),
330: (["Ampliar a jornada de trabalho para garantir a continuidade da assistência nos serviços","Incluir o trabalhador na gestão e reconhecer sua participação nos processos decisórios","Reduzir a autonomia das equipes para padronizar as condutas assistenciais adotadas","Padronizar as escalas de trabalho sem consulta prévia aos profissionais envolvidos","Restringir as ações de educação permanente aos profissionais em cargos de chefia"],1),
781: (["Idade superior a sessenta anos, em qualquer situação epidemiológica do território","Menores de seis meses, imunossupressão grave e anafilaxia prévia a ovo ou componentes","Gestação, em qualquer circunstância, sem possibilidade de avaliação individualizada","Uso de antibiótico por infecção bacteriana em curso no momento previsto para a dose","Doença crônica controlada com medicação de uso contínuo e acompanhamento regular"],1),
777: (["Reiniciar todo o esquema desde a primeira dose, desprezando as doses já aplicadas","Completar o esquema a partir das doses já recebidas, respeitando os intervalos mínimos","Aplicar todas as doses pendentes no mesmo atendimento, em sítios anatômicos distintos","Aguardar a próxima campanha nacional de multivacinação para regularizar a caderneta","Considerar a criança fora do calendário e encaminhá-la ao centro de referência estadual"],1),
769: (["Tempo de submersão referido por testemunhas presentes no momento do resgate","Achados na ausculta pulmonar e na avaliação circulatória e neurológica da vítima","Temperatura da água e condições ambientais no momento em que ocorreu o afogamento","Idade da vítima e presença de comorbidades cardiovasculares previamente conhecidas","Tipo de água envolvida, doce ou salgada, pelo distinto comportamento osmótico"],1),
762: (["Sentado, com as pernas pendentes, para reduzir o esforço respiratório do paciente","Decúbito dorsal com membros inferiores elevados, evitando mudanças bruscas de posição","Decúbito ventral, para prevenir a broncoaspiração em caso de vômito durante a crise","Posição de Trendelenburg invertida, com a cabeceira elevada acima de quarenta e cinco graus","Ortostatismo assistido, com apoio de dois profissionais durante toda a avaliação inicial"],1),
742: (["A máxima disponível no equipamento, para garantir a remoção completa das secreções","Ajustada dentro da faixa recomendada, evitando pressões excessivas que lesam a mucosa","Irrelevante para o procedimento, desde que o tempo de aspiração seja respeitado","Mantida sempre acima de trezentos milímetros de mercúrio em secreções espessas","Definida pelo próprio paciente conforme a tolerância referida durante o procedimento"],1),
730: (["Presença de tecido de granulação exuberante ocupando toda a extensão do leito","Aumento do exsudato e do odor, dor crescente, edema, calor e retardo da cicatrização","Redução progressiva das dimensões da lesão a cada avaliação semanal realizada","Bordas epitelizadas com avanço centrípeto do tecido de reepitelização da lesão","Ausência de exsudato com o leito da ferida limpo e de coloração vermelho vivo"],1),
699: (["Febre associada a diarreia aquosa e desidratação de instalação rápida na criança","Febre e exantema maculopapular acompanhados de tosse, coriza ou conjuntivite","Exantema isolado de início súbito, sem febre ou sintomas respiratórios associados","Tosse persistente por mais de três semanas acompanhada de perda ponderal progressiva","Febre acompanhada de artralgia intensa e incapacitante em grandes articulações"],1),
692: (["Aquecer rapidamente as extremidades com fricção vigorosa e imersão em água morna","Remover roupas úmidas, aquecer gradualmente e manipular com cuidado, pelo risco de arritmias","Oferecer bebidas alcoólicas para promover vasodilatação e sensação de aquecimento","Manter o paciente em ambiente ventilado e frio para evitar o reaquecimento acelerado","Realizar banho quente imediato por imersão para elevar rapidamente a temperatura central"],1),
589: (["Água tratada armazenada em reservatórios sem manutenção periódica adequada","Alimentos contaminados por fezes do triatomíneo, como açaí e caldo de cana","Carne bovina malpassada proveniente de abate sem inspeção sanitária oficial","Leite pasteurizado conservado fora da faixa de temperatura recomendada pelo fabricante","Frutas lavadas em água corrente sem uso de solução clorada para desinfecção prévia"],1),
465: (["Encerrar formalmente o cuidado prestado ao paciente ao término da internação","Verificar sistematicamente as mudanças nas respostas do paciente e ajustar o plano","Registrar as condições do paciente no momento da alta hospitalar ou da transferência","Substituir o diagnóstico de enfermagem inicialmente estabelecido por um novo julgamento","Documentar os procedimentos realizados pelos técnicos de enfermagem durante o plantão"],1),
438: (["Aceitá-las livremente sempre que houver necessidade de agilizar o cuidado prestado","Restringi-las a emergências, com repetição em voz alta para confirmação e registro posterior","Aceitá-las apenas quando transmitidas por telefone e confirmadas por um segundo profissional","Nunca aceitá-las, ainda que se trate de parada cardiorrespiratória em curso na unidade","Registrá-las somente ao final do plantão, junto com as demais anotações de enfermagem"],1),
819: (["Realizar toques vaginais frequentes para acompanhar a evolução da dilatação cervical","Evitar toques desnecessários, monitorar sinais de infecção e avaliar a vitalidade fetal","Estimular a deambulação prolongada para favorecer a progressão do trabalho de parto","Indicar banho de imersão em banheira para alívio do desconforto e relaxamento materno","Aguardar setenta e duas horas sem reavaliação, desde que a gestante permaneça assintomática"],1),
729: (["Recém-nascidos, pela imaturidade das camadas mais superficiais da pele e dos anexos","Pessoas idosas, por fragilidade da pele e menor adesão entre epiderme e derme","Adolescentes atletas submetidos a atrito repetido durante a prática esportiva regular","Gestantes no terceiro trimestre, pelo estiramento cutâneo e alteração da elasticidade","Pacientes cirúrgicos jovens em uso prolongado de adesivos e curativos oclusivos"],1),
717: (["Deve ser evitada para não gerar litígio e desgaste da imagem institucional do serviço","É recomendada, de forma transparente, com informação sobre o ocorrido e as medidas adotadas","Cabe exclusivamente ao setor jurídico da instituição, mediante avaliação prévia do caso","Ocorre somente nos casos que evoluírem para óbito ou dano permanente ao paciente","Depende de autorização judicial prévia para o fornecimento das informações à família"],1),
633: (["Uso de compressas geladas e banho frio para redução rápida da temperatura corporal","Antitérmico conforme prescrição, oferta de líquidos, roupas leves e observação de sinais de gravidade","Uso de ácido acetilsalicílico como primeira escolha pela ação antitérmica prolongada","Restrição da oferta hídrica para evitar sobrecarga durante o período febril da criança","Agasalhar a criança para induzir sudorese e favorecer a queda espontânea da temperatura"],1),
528: (["Registrar os acidentes de trabalho ocorridos no período e suas respectivas causas","Representar graficamente os riscos existentes nos setores, orientando medidas de prevenção","Definir o percentual de adicional de periculosidade devido a cada categoria profissional","Substituir a comunicação de acidente de trabalho nos casos sem afastamento do trabalhador","Controlar a frequência e a assiduidade dos trabalhadores nos setores de maior risco"],1),
414: (["Realizar a intubação orotraqueal imediatamente após o nascimento do recém-nascido","Prover calor, posicionar a cabeça, aspirar vias aéreas se necessário e secar o bebê","Administrar adrenalina por via endovenosa através do cateterismo da veia umbilical","Iniciar massagem cardíaca coordenada com a ventilação em pressão positiva controlada","Puncionar acesso venoso umbilical para reposição volêmica com solução cristaloide"],1),
347: (["Contratar servidores temporários para suprir a carência de profissionais na região","Formalizar as responsabilidades dos entes federativos na organização das redes regionais","Autorizar a transferência da gestão de unidades públicas para organizações sociais","Definir o piso salarial nacional das categorias profissionais que atuam no sistema","Regular a atuação dos planos privados de saúde no âmbito das regiões de saúde"],1),
837: (["Ser encaminhada ao serviço especializado somente se houver doença de base associada","Ter o caso investigado, com avaliação alimentar, social e clínica, e acompanhamento mais frequente","Aguardar a próxima consulta de rotina para confirmar a tendência observada na curva","Receber suplementação nutricional imediata, independentemente da avaliação clínica","Ser retirada do acompanhamento de puericultura e encaminhada à assistência social"],1),
791: (["Aguardar o término do período de amamentação para receber a dose em atraso","Ser vacinada no puerpério, pois a amamentação não contraindica a tríplice viral","Nunca ser vacinada, por se tratar de imunobiológico de agente vivo atenuado","Receber apenas imunoglobulina específica como alternativa segura durante a lactação","Ser vacinada somente após um ano do parto, quando cessar o risco de transmissão"],1),
789: (["Transportar os imunobiológicos em sacola comum, desde que o trajeto seja curto","Utilizar caixa térmica com bobinas ambientadas e termômetro, com registro das temperaturas","Dispensar o registro das doses aplicadas quando não houver acesso ao sistema no local","Manter as vacinas em temperatura ambiente durante a atividade, ao abrigo da luz solar","Levar frascos já abertos no dia anterior para reduzir a perda de doses do estoque"],1),
681: (["Administração de insulina em bolus repetidos até a normalização da glicemia capilar","Hidratação venosa, insulinoterapia e reposição de potássio, com monitorização eletrolítica","Restrição hídrica associada ao uso de bicarbonato de sódio de rotina em todos os casos","Hidratação exclusivamente por via oral, com oferta fracionada de líquidos sem açúcar","Uso isolado de antidiabético oral em dose plena até a resolução do quadro metabólico"],1),
}

for i, (opcoes, correta) in NOVAS.items():
    assert len(opcoes) == 5, i
    B[i]['o'] = [x.strip() for x in opcoes]
    B[i]['c'] = correta

def diff(q):
    c = len(q['o'][q['c']]); o = [len(x) for j, x in enumerate(q['o']) if j != q['c']]
    return c - max(o)

print(f"correta é a mais longa: {sum(1 for q in B if diff(q) > 0)}/{len(B)} = {sum(1 for q in B if diff(q) > 0)/len(B)*100:.1f}%")
print(f"excede a 2ª maior em >20 chars: {sum(1 for q in B if diff(q) > 20)}")
print(f"excede em >40 chars: {sum(1 for q in B if diff(q) > 40)}")

linhas = []
for q in B:
    partes = [f'a:{json.dumps(q["a"], ensure_ascii=False)}',
              f't:{json.dumps(q["t"], ensure_ascii=False)}',
              f'q:{json.dumps(q["q"], ensure_ascii=False)}',
              'o:[' + ','.join(json.dumps(x, ensure_ascii=False) for x in q['o']) + ']',
              f'c:{q["c"]}',
              f'e:{json.dumps(q["e"], ensure_ascii=False)}',
              f'f:{json.dumps(q["f"], ensure_ascii=False)}']
    linhas.append('{' + ','.join(partes) + '}')

novo = 'const BANCO = [\n' + ',\n'.join(linhas) + '\n];'
s = open('index.html', encoding='utf-8').read()
s2 = re.sub(r'const BANCO = \[.*?\n\];', lambda m: novo, s, count=1, flags=re.S)
assert s2 != s
open('index.html', 'w', encoding='utf-8').write(s2)
print("banco regravado:", len(B), "questões")
